<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FirearmsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $item =[
            ['name' => 'AYONET FOR HK-33',
            'code' => 'wp01',
            'stock' => '100',
            'type' => '5',
            'images' => '/image/item/image1.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'RIFLE AUTOMATIC 5.56 MM. HK-33',
            'code' => 'wp02',
            'stock' => '100',
            'type' => '1',
            'images' => '/image/item/image2.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'MAGAZINE FOR HK-33 [40 RD]',
            'code' => 'wp03',
            'stock' => '200',
            'type' => '4',
            'images' => '/image/item/image3.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'MACHINE GUN 7.62 MM. M60',
            'code' => 'wp04',
            'stock' => '30',
            'type' => '1',
            'images' => '/image/item/image4.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'AUTOMATIC PISTOL 9 MM. FN',
            'code' => 'wp05',
            'stock' => '20',
            'type' => '3',
            'images' => '/image/item/image5.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'MAGAZINE PISTOL CAL. 9 MM.',
            'code' => 'wp06',
            'stock' => '20',
            'type' => '4',
            'images' => '/image/item/image6.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'CARBINE AUTOMATIC CAL.5.56 MM. M4A3',
            'code' => 'wp07',
            'stock' => '100',
            'type' => '1',
            'images' => '/image/item/image7.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'MAGAZINE FOR M4A3 [20 RD]',
            'code' => 'wp08',
            'stock' => '200',
            'type' => '4',
            'images' => '/image/item/image8.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'SHOT GUN 12 GAGE SAVACE M69E',
            'code' => 'wp09',
            'stock' => '50',
            'type' => '1',
            'images' => '/image/item/image9.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'RIFLE AUTOMATIC CAL. 5.56MM. M16A1',
            'code' => 'wp10',
            'stock' => '100',
            'type' => '1',
            'images' => '/image/item/image10.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'MAGAZINE FOR M16A1 [20 RD]',
            'code' => 'wp11',
            'stock' => '200',
            'type' => '4',
            'images' => '/image/item/image11.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'RIFLE, AUTOMATIC, CAL.5.56 MM.,M16A4',
            'code' => 'wp12',
            'stock' => '20',
            'type' => '1',
            'images' => '/image/item/image12.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'MAGAZINE FOR RIFLE, AUTOMATIC',
            'code' => 'wp13',
            'stock' => '40',
            'type' => '4',
            'images' => '/image/item/image13.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'LAUNCHER GRENADE 40 MM.TSB',
            'code' => 'wp14',
            'stock' => '20',
            'type' => '2',
            'images' => '/image/item/image14.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'RIFLE CAL. .22 MAUSER',
            'code' => 'wp15',
            'stock' => '20',
            'type' => '1',
            'images' => '/image/item/image15.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'AUTOMATIC PISTOL .45 MM. COLT',
            'code' => 'wp16',
            'stock' => '20',
            'type' => '3',
            'images' => '/image/item/image16.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'MAGAZINE PISTOL CAL. .45',
            'code' => 'wp17',
            'stock' => '40',
            'type' => '4',
            'images' => '/image/item/image17.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'GLOCK 18',
            'code' => 'wp18',
            'stock' => '20',
            'type' => '3',
            'images' => '/image/item/image18.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'MAGAZINE PISTOL FOR GLOCK 18',
            'code' => 'wp19',
            'stock' => '40',
            'type' => '4',
            'images' => '/image/item/image19.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
            ['name' => 'MACHINE GUN 7.62 MM. M60 E6',
            'code' => 'wp20',
            'stock' => '30',
            'type' => '1',
            'images' => '/image/item/image20.png',
            'created_by' => 'system',
            'created_at' => now(),
            'updated_by' => 'system',
            'updated_at' => now(),
            ],
        ];
        DB::table('firearms')->insert($item);
    }
}     